spring:
  datasource:
    url: jdbc:mysql://192.168.8.82:3306/ocean?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.matrixstudio: debug
    org.springframework.security: debug

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"
